function humanTimeDiff(from,to){'use strict';var MINUTE_IN_SECONDS=60,HOUR_IN_SECONDS=MINUTE_IN_SECONDS*60,DAY_IN_SECONDS=HOUR_IN_SECONDS*24,WEEK_IN_SECONDS=DAY_IN_SECONDS*7,since='',time;if(!(to instanceof Date)){to=new Date();}
var diff=Math.abs((to/1000)-(from/1000));if(diff<HOUR_IN_SECONDS){time=Math.round(diff/MINUTE_IN_SECONDS);if(time<=1){time=1;}
since=time+' minute'+((time>1)?'s':'')+' ago';}else if(diff<DAY_IN_SECONDS&&diff>=HOUR_IN_SECONDS){time=Math.round(diff/HOUR_IN_SECONDS);if(time<=1){time=1;}
since=time+' hour'+((time>1)?'s':'')+' ago';}else if(diff<WEEK_IN_SECONDS&&diff>=DAY_IN_SECONDS){time=Math.round(diff/DAY_IN_SECONDS);if(time<=1){time=1;}
since=time+' day'+((time>1)?'s':'')+' ago';}
return since;};(function(d,$){'use strict';var socialController=new ScrollMagic.Controller(),shareScene;function updateSharePanel(){if(window.matchMedia('(min-width: 64em)').matches){shareScene.enabled(true);}else{shareScene.enabled(false);}}
function initSharePanel(){var $=jQuery,$ntShare=$('.nt-share'),$wrap=$('.page-content-wrap');if($ntShare.length){var magic=40,socialDuration=$wrap.outerHeight()-
($ntShare.outerHeight()*2+magic);shareScene=new ScrollMagic.Scene({duration:socialDuration,triggerElement:$('.page-content-wrap')[0]}).setPin($ntShare[0]).addTo(socialController);updateSharePanel();$(window).resize(function(){updateSharePanel();});}}
$(function(){var $slider=$('.slider'),$iframes=$('.holiday-media iframe');$('.search-input').focus(function(){$(this).addClass('has-focus');}).blur(function(){$(this).removeClass('has-focus');});$('#user-icon').mouseenter(function(){$('#user-icon g').css({fill:"#f33f33"});});$('#search-icon').mouseenter(function(){$('#search-icon g').css({fill:"#f33f33"});});$('#search-toggle').click(function(e){e.preventDefault();var $c=$('#header-search'),$b=$(this);if($c.hasClass('toggled')){$b.attr('aria-expanded','false');$c.removeClass('toggled').attr('aria-expanded','false');$('#menu-primary-fall-2018, #headerAccount').css({opacity:'1'});}else{$b.attr('aria-expanded','true');$c.addClass('toggled').attr('aria-expanded','true');$c.find('input[type="search"]').focus();$('#menu-primary-fall-2018, #headerAccount').css({opacity:'0'});}});$('#catSearchToggle').click(function(e){e.preventDefault();var $c=$('#catSearch'),$b=$(this);if($c.hasClass('toggled')){$b.attr('aria-expanded','false');$c.removeClass('toggled').attr('aria-expanded','false');$('.news-cat-container').css({opacity:'1'});}else{$b.attr('aria-expanded','true');$c.addClass('toggled').attr('aria-expanded','true');$c.find('input[type="search"]').focus();$('.news-cat-container').css({opacity:'0'});}});$('#mobile-catSearchToggle').click(function(e){e.preventDefault();var $c=$('#mobile-catSearch'),$b=$(this);if($c.hasClass('toggled')){$b.attr('aria-expanded','false');$c.removeClass('toggled').attr('aria-expanded','false');$('.news-cat-container').css({opacity:'1'});}else{$b.attr('aria-expanded','true');$c.addClass('toggled').attr('aria-expanded','true');$c.find('input[type="search"]').focus();$('.news-cat-container').css({opacity:'0'});}});if($slider.length){$('.slider').slick({arrows:true,nextArrow:'<i class="fas fa-chevron-right"></i>',prevArrow:'<i class="fas fa-chevron-left"></i>',dots:false});}
if($iframes.length){$iframes.attr({'height':'100%','width':'100%'});}
var currLoc=window.location.origin;$('a').each(function(idx,link){var href=link.href,rel,newRel;if(href.indexOf(currLoc)!==0){rel=link.getAttribute('rel');newRel=(rel)?rel.toLowerCase().split(' '):[];if($.inArray('noopener',newRel)===-1){newRel.push('noopener');}
link.setAttribute('rel',$.trim(newRel.join(' ')));}});});var faqPanels=Array.prototype.slice.call(document.getElementsByClassName('faq-section'));if(faqPanels){var toggleAccordion=function toggleAccordion(e){var target=e.target;if(target.classList.contains('accordion-btn')){target.classList.toggle('active');target.nextElementSibling.classList.toggle('active');target.children[0].classList.toggle('rotate-icon');}};faqPanels.forEach(function(faq){faq.addEventListener('click',toggleAccordion);});}
var translationPanel=Array.prototype.slice.call(document.getElementsByClassName('panel-content'));if(translationPanel){let toggleAccordion=function toggleAccordion(e){let target=e.target;if(target.classList.contains('accordion-btn')){$('.holiday-translations-container').toggleClass('translations-active')
target.classList.toggle('active');target.nextElementSibling.classList.toggle('active');target.children[0].classList.toggle('rotate-icon');}};translationPanel.forEach(function(translation){translation.addEventListener('click',toggleAccordion);});}
var now=new Date();$('.js-relative-date').each(function(idx,val){var $val=$(val),then=new Date($val.attr('datetime')),since=humanTimeDiff(now,then);if(since){$val.text(since);}
$val.css('visibility','visible');});}(document,jQuery));var controller=new ScrollMagic.Controller();var nt={setConsistentHeight:function setConsistentHeight(sel){var $el=$(sel),maxHeight=0;$el.css('height','auto');$el.each(function(){var height=$(this).height();if(height>maxHeight){maxHeight=height;}});$el.height(maxHeight);},setConsistentHeights:function setConsistentHeights(sels){for(var i=0,l=sels.length;i<l;i++){nt.setConsistentHeight(sels[i]);}}};jQuery(document).ready(function($){if($('.holiday-enhanced-content .holiday-section').length){$('.holiday-enhanced-content').addClass('animated');$('.holiday-enhanced-content').find('.holiday-section').each(function(){var el=$(this)[0];new ScrollMagic.Scene({triggerElement:el,triggerHook:0.7,reverse:false}).setClassToggle(el,"active").addTo(controller);});$('.holiday-timeline-list').find('.holiday-timeline-date').each(function(){var date=$(this)[0];var desc=$(this).next('.holiday-timeline-desc')[0];new ScrollMagic.Scene({triggerElement:date,triggerHook:0.85,reverse:false}).setClassToggle([date,desc],"active").addTo(controller);});$('.holiday-list').find('li').each(function(){var el=$(this)[0];new ScrollMagic.Scene({triggerElement:el,triggerHook:0.85,reverse:false}).setClassToggle(el,"active").addTo(controller);});}
if($('.home-enhanced-content .home-section').length){$('.home-enhanced-content').addClass('animated');$('.home-enhanced-content').find('.home-section').each(function(){var el=$(this)[0];new ScrollMagic.Scene({triggerElement:el,triggerHook:0.7,reverse:false}).setClassToggle(el,"active").addTo(controller);});}
var celebrateHeadlineSelectors=['.celebrate-post-wide .celebrate-post-content dd','.celebrate-post-normal .celebrate-post-content dd'];nt.setConsistentHeights(celebrateHeadlineSelectors);$(window).on('resize',nt.setConsistentHeights.bind(nt,celebrateHeadlineSelectors));var articleHeaderHeight=$('#contentHeader').outerHeight(true);var pageContentHeight=$('.site-content').outerHeight();var siteHeaderHeight=$('.site-header').outerHeight(true);var siteHeaderHeightInner=$('.site-header').outerHeight(false);var postThumbnail=$('.post-thumbnail').outerHeight();var thisContainer=this;$.fn.followTo=function(pos){var $this=this,$window=$(thisContainer);$window.scroll(function(e){if($window.scrollTop()>pos){$this.css({opacity:0,});}else{$this.css({position:'fixed',top:(articleHeaderHeight+siteHeaderHeight)-20,opacity:1,});}});};if(document.querySelector('.page-template-Template-What-Is')!==null){$('.nt-share').followTo(pageContentHeight-postThumbnail-siteHeaderHeightInner);}else{$('.nt-share').followTo(pageContentHeight-postThumbnail);}
$(window).load(function(){$('.nt-share').css({top:(articleHeaderHeight+siteHeaderHeight)-20});$('.nt-share').animate({opacity:1});$('#newsAside').animate({opacity:1});});$(window).scroll(function(){if($(document).scrollTop()>50){$('#mobileNT').addClass('nt-scrolled');}else{$('#mobileNT').removeClass('nt-scrolled');}
if($(document).scrollTop()>pageContentHeight-window.innerHeight){$('#mobileNT').removeClass('nt-scrolled');}});$('.kebab .figure-container').click(function(){$('.middle, .left, .right, .cross, .news-cats-list').toggleClass('active');});});